import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Icon } from "@/components/icons";
import { SectionHeading } from "@/components/section-heading";

export const metadata: Metadata = { title: "O nás", description: "ŠTENCEL TRANSPORT zajišťuje vnitrostátní a mezinárodní dopravu a spedici od roku 1993.", alternates: { canonical: "/o-nas" } };

export default function AboutPage() { return <main id="obsah"><section className="subhero"><div className="container"><span className="eyebrow light">O společnosti</span><h1>Na cestě od roku 1993.</h1><p>Česká dopravní společnost s pobočkami napříč republikou a působností v Evropě.</p></div></section><section className="section"><div className="container split"><div><SectionHeading eyebrow="Kdo jsme" title="Zkušenost, na kterou se dá navázat." /><p>ŠTENCEL TRANSPORT s. r. o. působí v silniční dopravě od roku 1993. Zajišťuje vnitrostátní i mezinárodní přepravu a spediční služby pro zákazníky v České republice a Evropě.</p><p>Za každou trasou stojí konkrétní dispečer, znalost provozu a dlouhodobá spolupráce s vlastními i smluvními dopravci. Důraz klademe na přímou komunikaci, bezpečnost nákladu a přehled o průběhu přepravy.</p></div><div className="about-photo"><Image src="/images/spedition.avif" alt="Areál společnosti Štencel Transport v Oticích" fill sizes="(max-width: 900px) 100vw, 48vw" /></div></div></section><section className="dark-section"><div className="container"><SectionHeading eyebrow="Naše zázemí" title="Čtyři dispečinky. Jeden standard služby." light /><div className="stats"><div><strong>1993</strong><span>rok založení</span></div><div><strong>4</strong><span>dispečinky v ČR</span></div><div><strong>EU</strong><span>evropská působnost</span></div></div></div></section><section className="section"><div className="container split"><div className="process-photo"><Image src="/images/domestic.avif" alt="Kamion společnosti Štencel Transport" fill sizes="(max-width: 900px) 100vw, 45vw" /></div><div><SectionHeading eyebrow="Jak pracujeme" title="Technika a lidé v jednom rytmu." /><p>Vozidla využívají GPS monitoring a dispečink sleduje průběh přepravy. Pro mimořádně hodnotné zásilky lze individuálně řešit připojištění.</p><Link href="/kontakty" className="text-link">Poznat naše dispečinky <Icon name="arrow" /></Link></div></div></section></main>; }
