import Image from "next/image";
import Link from "next/link";
import { Icon } from "@/components/icons";
import { SectionHeading } from "@/components/section-heading";
import { services } from "@/lib/site";

export default function Home() {
  return <main id="obsah">
    <section className="hero">
      <Image src="/images/hero.avif" alt="Kamion Štencel Transport na cestě" fill priority sizes="100vw" className="hero-image" />
      <div className="hero-overlay" />
      <div className="container hero-content"><span className="eyebrow light">Česká dopravní společnost od roku 1993</span><h1>Doprava bez<br /><em>zbytečných odboček.</em></h1><p>Vnitrostátní a mezinárodní silniční přeprava i spedice. Váš náklad držíme pod dohledem od nakládky až do cíle.</p><div className="hero-actions"><Link className="button" href="/poptavka">Poptat přepravu <Icon name="arrow" /></Link><a className="button button-ghost" href="tel:+420606712552"><Icon name="phone" /> Nonstop dispečink</a></div></div>
      <div className="hero-rail"><span>24/7 dispečink</span><span>ČR &amp; Evropa</span><span>GPS monitoring</span></div>
    </section>
    <section className="quick-contact"><div className="container quick-grid"><div><span className="pulse" />Potřebujete nacenit přepravu?</div><p>Řekněte nám odkud, kam a co povezeme. Ozveme se s řešením.</p><Link href="/poptavka">Rychlá poptávka <Icon name="arrow" /></Link></div></section>
    <section className="section" id="sluzby"><div className="container"><SectionHeading eyebrow="Co pro vás zajistíme" title="Jedna trasa. Tři cesty k řešení." text="Od pravidelných vnitrostátních linek po evropskou přepravu a flexibilní spedici." /><div className="services-grid">{services.map((service, index) => <Link href={`/${service.slug}`} className="service-card" key={service.slug}><div className="service-image"><Image src={service.image} alt="" fill sizes="(max-width: 800px) 100vw, 33vw" /></div><div className="service-number">0{index + 1}</div><div className="service-body"><span>{service.eyebrow}</span><h3>{service.title}</h3><p>{service.text}</p><b>Detail služby <Icon name="arrow" /></b></div></Link>)}</div></div></section>
    <section className="dark-section"><div className="container"><SectionHeading eyebrow="Proč Štencel Transport" title="Přehled v každém kilometru." text="Zkušený tým, průběžná komunikace a technologie, které pomáhají držet přepravu v pohybu." light /><div className="benefits"><article><Icon name="route" /><h3>GPS monitoring</h3><p>Aktuální přehled o pohybu vozidel a zásilek během přepravy.</p></article><article><Icon name="shield" /><h3>Bezpečnost nákladu</h3><p>Proškolení řidiči a možnost individuálního připojištění mimořádně hodnotných zásilek.</p></article><article><Icon name="clock" /><h3>Dispečink 24/7</h3><p>Kontaktní osoby napříč čtyřmi dispečinky jsou připravené řešit provozní situace.</p></article></div><div className="stats"><div><strong>1993</strong><span>rok založení</span></div><div><strong>EU</strong><span>evropská působnost</span></div><div><strong>24/7</strong><span>nonstop dispečink</span></div></div></div></section>
    <section className="section process"><div className="container split"><div><SectionHeading eyebrow="Jak to probíhá" title="Od poptávky k vykládce ve čtyřech krocích." /><ol className="steps"><li><b>01</b><div><h3>Zadáte trasu a náklad</h3><p>Stačí základní údaje o nakládce, vykládce a zásilce.</p></div></li><li><b>02</b><div><h3>Navrhneme řešení</h3><p>Dispečer ověří kapacitu a připraví vhodný způsob přepravy.</p></div></li><li><b>03</b><div><h3>Přepravu sledujeme</h3><p>GPS monitoring a přímá komunikace pomáhají držet průběh pod kontrolou.</p></div></li><li><b>04</b><div><h3>Doručíme do cíle</h3><p>Po vykládce uzavřeme přepravu a předáme potřebné podklady.</p></div></li></ol></div><div className="process-photo"><Image src="/images/international.avif" alt="Vozový park Štencel Transport" fill sizes="(max-width: 900px) 100vw, 45vw" /><div><span>Technika v pohybu</span><strong>Vozový park s průběžným GPS dohledem</strong></div></div></div></section>
    <section className="section about"><div className="container split"><div className="about-photo"><Image src="/images/spedition.avif" alt="Areál společnosti Štencel Transport v Oticích" fill sizes="(max-width: 900px) 100vw, 48vw" /></div><div><SectionHeading eyebrow="O společnosti" title="Rodinná tradice, profesionální logistika." /><p>ŠTENCEL TRANSPORT působí v silniční dopravě od roku 1993. Z českých poboček zajišťuje vnitrostátní i mezinárodní přepravu a spedici napříč Evropou.</p><Link className="text-link" href="/o-nas">Více o společnosti <Icon name="arrow" /></Link></div></div></section>
    <section className="service-cta"><div className="container"><div><span className="eyebrow light">Máte trasu?</span><h2>My najdeme cestu.</h2></div><div><Link href="/poptavka" className="button">Zadat poptávku <Icon name="arrow" /></Link><Link href="/kontakty">Kontakty na dispečinky</Link></div></div></section>
  </main>;
}
